#! /usr/bin/env python3

import argparse
import importlib
import numpy as np
import utils

np.random.seed(20197416)

models = utils.list_models()

parser = argparse.ArgumentParser(prog='ml-sandbox')
parser.add_argument('model_name', help='<model-name>', choices=models, type=str)
parser.add_argument('-l, --learning-rate', dest='learning_rate', help='The learning rate for the optimizer', type=float, default=0.01)
parser.add_argument('-d, --decay', dest='learning_rate_decay', help='The learning rate decay', type=float, default=0)
parser.add_argument('-n, --epochs', dest='num_epochs', help='The number of epochs to train the model', type=int, default=1000)

params = parser.parse_args();

module = importlib.import_module('models.' + params.model_name)

model = module.train_model(params)

utils.save_model(model, params)
  

