#! /usr/bin/env bash

TF_TAG="1.13.1-py3"
IMAGE_TAG="cpu"
RUNTIME=""

for arg in "$@"; do
  case "$arg" in
    -g|--gpu*)
      TF_TAG="1.13.1-gpu-py3"
      IMAGE_TAG="gpu"
      RUNTIME="--runtime=nvidia"
      ;;
  esac
done

docker build --build-arg tensorflow_tag=$TF_TAG --tag ml-sandbox:$IMAGE_TAG `pwd`

# -u set user id
# -v -w mount cwd and cd into it
# -it interactive tty
# --rm auto remove on exit
# [--runtime] add gpu runtime if necessary

docker run \
  -u $(id -u):$(id -g) \
  -v `pwd`:`pwd` \
  -w `pwd` \
  -it \
  --rm \
  $RUNTIME \
  ml-sandbox:$IMAGE_TAG \
  bash