#! /usr/bin/env bash

IMAGE_NAME="ml-cpu"
TF_TAG="1.13.1-py3"
RUNTIME=""

for arg in "$@"; do
  case "$arg" in
    -g|--gpu*)
      IMAGE_NAME="ml-gpu"
      TF_TAG="1.13.1-gpu-py3"
      RUNTIME="--runtime=nvidia"
      ;;
  esac
done

docker build --build-arg tensorflow_tag=$TF_TAG --tag $IMAGE_NAME `pwd`

# -u set user id
# --env and first few volumes give access to X11 on host so we can plot using matplotlib 
# -v -w mount cwd and cd into it
# -it interactive tty
# --rm auto remove on exit
# [--runtime] add gpu runtime if necessary

docker run \
  -u $(id -u):$(id -g) \
  --env="DISPLAY" \
  -v "/etc/group:/etc/group:ro" \
  -v "/etc/passwd:/etc/passwd:ro" \
  -v "/etc/shadow:/etc/shadow:ro" \
  -v "/etc/sudoers.d:/etc/sudoers.d:ro" \
  -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  -v `pwd`:`pwd` \
  -w `pwd` \
  -it \
  --rm \
  $RUNTIME $IMAGE_NAME \
  bash